USE [master]
GO

/****** Object:  Database [StudentCourses]    Script Date: 5/7/2021 10:44:09 AM ******/
DROP DATABASE [StudentCourses]
GO

/****** Object:  Database [StudentCourses]    Script Date: 5/7/2021 10:44:09 AM ******/
CREATE DATABASE [StudentCourses]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ServiceBrokerTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ServiceBrokerTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ServiceBrokerTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ServiceBrokerTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StudentCourses].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StudentCourses] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StudentCourses] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StudentCourses] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StudentCourses] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StudentCourses] SET ARITHABORT OFF 
GO

ALTER DATABASE [StudentCourses] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [StudentCourses] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StudentCourses] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StudentCourses] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StudentCourses] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StudentCourses] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StudentCourses] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StudentCourses] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StudentCourses] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StudentCourses] SET  ENABLE_BROKER 
GO

ALTER DATABASE [StudentCourses] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StudentCourses] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StudentCourses] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StudentCourses] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StudentCourses] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StudentCourses] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StudentCourses] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StudentCourses] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StudentCourses] SET  MULTI_USER 
GO

ALTER DATABASE [StudentCourses] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StudentCourses] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StudentCourses] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StudentCourses] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StudentCourses] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StudentCourses] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StudentCourses] SET QUERY_STORE = OFF
GO

ALTER DATABASE [StudentCourses] SET  READ_WRITE 
GO


